import type { ContentSnapshot } from '@monorepo/content-schema';

export const demoContent: ContentSnapshot = {
  version: 'demo-1',
  updatedAt: new Date('2026-06-17T00:00:00.000Z').toISOString(),
  settings: {
    phoneDisplay: '050-3502615',
    phoneHref: 'tel:+972503502615',
    email: 'nisboutiquecatering@gmail.com',
    whatsappBase: 'https://wa.me/972503502615',
    siteVersion: 'v0.1.2',
    seoTitle: 'Nis Boutique Catering',
    seoDescription: 'קייטרינג בוטיק ביתי לשבתות ואירועים קטנים',
  },
  media: [
    {
      id: 'hosting-table-overview',
      src: '/media/food/events/quiche-tart-clean.webp',
      width: 721,
      height: 1280,
      sizes: '(max-width: 720px) 100vw, 50vw',
      responsive: true,
      usageNotes: 'Hero, gallery, signature moment',
    },
    {
      id: 'mini-burger-trays',
      src: '/media/food/events/mini-burger-trays.webp',
      width: 899,
      height: 1599,
      sizes: '(max-width: 720px) 100vw, 33vw',
      responsive: true,
      usageNotes: 'Travel Nis and tray gallery',
    },
  ],
  gallery: [
    {
      id: 'hosting-table-overview',
      title: 'שולחן אירוח מוכן',
      alt: 'שולחן אירוח מסודר עם מגשי ירקות, סלטים, כריכונים וכלי הגשה',
      category: 'tables',
      order: 1,
      active: true,
      tall: true,
      mediaId: 'hosting-table-overview',
    },
    {
      id: 'mini-burger-trays',
      title: 'מיני לחמניות אישיות',
      alt: 'מגשים שחורים עם מיני לחמניות אישיות, שומשום, ירקות וסיכות במבוק',
      category: 'trays',
      order: 2,
      active: true,
      tall: true,
      mediaId: 'mini-burger-trays',
    },
  ],
  services: [
    {
      id: 'shabbat',
      title: 'ניס בטעם של שבת',
      subtitle: 'להכניס את השבת ברוגע, להתענג על הטעם.',
      description: 'תפריט שבת עשיר שמגיע מוכן, מסודר וברור להגשה.',
      bestFor: 'משפחות ומארחים שרוצים שבת רגועה.',
      promise: 'מגיע מוכן, מסודר וברור להגשה.',
      details: ['סלטים', 'דגים', 'עיקריות', 'תוספות'],
      cta: 'להזמנת תפריט שבת',
      mediaId: 'hosting-table-overview',
      icon: 'ChefHat',
    },
  ],
  sections: [
    {
      id: 'hero',
      group: 'hero',
      title: 'קייטרינג בוטיק ביתי לשבתות ואירועים קטנים',
      text: 'שבתות, מגשי אירוח ו-Travel Nis, עם אוכל מוקפד ונראות יפה.',
      items: [],
      active: true,
    },
  ],
};
