import {
  CalendarDays,
  CheckCircle2,
  ChefHat,
  ClipboardList,
  HeartHandshake,
  MapPin,
  MessageCircle,
  Package,
  Phone,
  Sparkles,
  Users,
  Utensils,
  type LucideIcon,
} from 'lucide-react';
import type { SiteSectionPreviewData } from './SiteSectionPreviewData';

const image = (
  src: string,
  width: number,
  height: number,
  sizes?: string,
  responsive = true,
) => ({
  src,
  width,
  height,
  sizes,
  responsive,
});

const fallbackFoodImage = image(
  '/media/food/events/quiche-tart-clean.webp',
  721,
  1280,
  '(max-width: 720px) 100vw, 50vw',
);

const card = (title: string, text: string, icon: LucideIcon) => ({ title, text, icon });

export const fallbackSiteSectionPreviewData: SiteSectionPreviewData = {
  audienceCards: [
    card('אירוח משפחתי', 'מתאים לאירוח ביתי מוקפד ונעים.', Users),
    card('אירוע קטן', 'חוויית אירוח מסודרת עם נראות טובה.', HeartHandshake),
    card('מארזים לדרך', 'פתרון נוח, טעים ומכובד ליציאה מהבית.', Package),
  ],
  brandMedia: {
    logo: image('/brand/nis-logo-20260619.svg', 1060, 610, '(max-width: 720px) 220px, 320px', false),
    socialCard: image('/brand/nis-logo-card.jpg', 945, 630, '(max-width: 720px) 100vw, 50vw'),
  },
  boutiqueReasons: [
    card('התאמה אישית', 'שיחה קצרה מחדדת מהר את כיוון האירוח.', ClipboardList),
    card('הגשה מסודרת', 'מגיע מוכן ונוח לפתיחה ולהגשה.', Sparkles),
    card('יחס אישי', 'תיאום אנושי ונעים לפני הסגירה.', HeartHandshake),
  ],
  contactDeliveryOptions: ['נדבר ונבדוק יחד', 'איסוף מביתר עילית', 'משלוח בתיאום'],
  contactInterestOptions: ['ניס בטעם של שבת', 'ניס בכיס', 'Travel Nis', 'אירוע קטן'],
  coordinationCards: [
    card('אזור פעילות', 'ביתר עילית והסביבה בתיאום.', MapPin),
    card('זמינות', 'כדאי לפנות מוקדם לשבתות ואירועים.', CalendarDays),
    card('תיאום הזמנה', 'מחדדים כמות, תאריך וסגנון הגשה.', ClipboardList),
  ],
  editorialCards: [
    { label: 'שבתות', title: 'אוכל ביתי מוקפד לשבת', text: 'תפריט שמגיע מוכן ורגוע להגשה.', icon: ChefHat, image: fallbackFoodImage },
    { label: 'אירוח קטן', title: 'מגשי אירוח ופינגר פוד', text: 'הגשה מוקפדת לאירועים קטנים.', icon: Sparkles, image: fallbackFoodImage },
    { label: 'Travel Nis', title: 'מארזים לדרך', text: 'פינוק שלוקחים איתכם הלאה.', icon: Package, image: fallbackFoodImage },
  ],
  faqs: [
    { question: 'איך מתחילים?', answer: 'משאירים פנייה קצרה ומקבלים כיוון מותאם.' },
    { question: 'אפשר התאמות?', answer: 'כן, לפי סוג האירוח, הכמות והתאריך.' },
  ],
  foodMedia: {
    hostingTableOverview: fallbackFoodImage,
    salmonSkewersLemon: image('/media/food/events/salmon-skewers-lemon.webp', 1500, 2000, '(max-width: 720px) 100vw, 45vw'),
    tableSettingBlueGold: image('/media/food/events/table-setting-blue-gold.webp', 1500, 2000, '(max-width: 720px) 100vw, 33vw'),
    dipsTrayClose: image('/media/food/events/dips-tray-close.webp', 1500, 2000, '(max-width: 720px) 100vw, 33vw'),
    miniSandwiches: image('/media/food/events/mini-burger-trays.webp', 899, 1599, '(max-width: 720px) 100vw, 33vw'),
  },
  galleryCategories: [
    { id: 'all', label: 'הכל' },
    { id: 'tables', label: 'שולחנות' },
    { id: 'trays', label: 'מגשים' },
    { id: 'salads', label: 'סלטים' },
    { id: 'fish', label: 'דגים' },
    { id: 'coffee', label: 'קפה' },
  ],
  galleryImages: [
    {
      title: 'שולחן אירוח',
      alt: 'שולחן אירוח מוכן',
      image: fallbackFoodImage,
      category: 'tables',
      tall: true,
    },
  ],
  heroBadges: ['שבתות', 'מגשי אירוח', 'Travel Nis'],
  heroContent: {
    eyebrow: 'קייטרינג בוטיק ביתי',
    title: 'אוכל מוקפד לשבתות ואירועים קטנים',
    kicker: 'חוויה ביתית עם נראות מסודרת ושיחה קצרה שסוגרת כיוון.',
    text: 'ה-preview בסטודיו נשען קודם כול על תוכן ה-snapshot, וה-fallback הזה קיים רק כדי לשמור על יציבות התצוגה.',
  },
  heroMedia: {
    background: fallbackFoodImage,
    primary: image('/media/food/events/salmon-skewers-lemon.webp', 1500, 2000, '(max-width: 720px) 100vw, 45vw'),
    side: image('/media/food/events/dips-tray-close.webp', 1500, 2000, '(max-width: 720px) 100vw, 33vw'),
    tall: image('/media/food/events/table-setting-blue-gold.webp', 1500, 2000, '(max-width: 720px) 100vw, 33vw'),
  },
  heroSceneNotes: [
    { title: 'נראות מוקפדת', text: 'שולחן שנראה מוכן כבר מהפתיחה.' },
    { title: 'טעם ביתי', text: 'אוכל חם, נעים ומכבד.' },
  ],
  heroStats: [
    { value: '3', label: 'חוויות אירוח ברורות' },
    { value: '1', label: 'שיחה קצרה לסגירת כיוון' },
  ],
  manifestoMoments: [
    { label: '01', title: 'שולחן שנראה נכון', text: 'נראות היא חלק מהחוויה.', image: fallbackFoodImage },
    { label: '02', title: 'טעם ביתי', text: 'אוכל שמרגיש מוכר וחגיגי.', image: fallbackFoodImage },
  ],
  menuGroups: [
    { title: 'תפריט שבת לדוגמה', intro: 'כיוון כללי לשולחן שבת.', items: ['סלטים', 'דגים', 'עיקריות', 'תוספות'] },
    { title: 'מגשי אירוח', intro: 'פתרון לאירוח קטן.', items: ['מאפים', 'כריכונים', 'מגשים מלוחים'] },
  ],
  phoneHref: 'tel:+972503502615',
  processSteps: [
    card('שולחים הודעה', 'וואטסאפ או טופס מסודר.', MessageCircle),
    card('מחדדים כיוון', 'סוג אירוח, תאריך וכמות.', CalendarDays),
    card('מקבלים הצעה', 'כיוון מותאם לאירוח.', ClipboardList),
    card('סוגרים פרטים', 'מגיע מוכן להגשה.', CheckCircle2),
  ],
  sectionCopy: {
    introBand: { eyebrow: 'רעיון אחד ברור', title: 'אוכל ביתי מוקפד, בהגשה של בוטיק.', text: 'שלוש חוויות ברורות, אותה שפה של אירוח.' },
    manifesto: { eyebrow: 'השפה של Nis', title: 'אירוח שנראה כמו מחשבה.', text: 'כשזה נראה נכון, זה מרגיש רגוע יותר.' },
    editorial: { eyebrow: 'מה מזמינים', title: 'קטגוריות ברורות לאירוח.' },
    audience: { eyebrow: 'למי זה מתאים', title: 'למי שרוצה לארח יפה בלי לסחוב הכול לבד.', text: 'שבת, אירוע קטן או מארז לדרך.' },
    experienceLab: { eyebrow: 'בחרו חוויה', title: 'מהרגע שבוחרים כיוון, האירוח מקבל צורה.', text: 'ה-preview עוזר להבין את ההגשה.' },
    signature: { eyebrow: 'למה זה בוטיק', title: 'פרטים קטנים שמרגישים נכון יותר.' },
    boutique: { eyebrow: 'למה זה מרגיש בוטיק', title: 'נראות, התאמה אישית ויחס אנושי.', text: 'שילוב בין טעם ביתי לגימור מוקפד.' },
    services: { eyebrow: 'מה אפשר להזמין', title: 'שלוש אפשרויות ברורות.', text: 'בוחרים כיוון וממשיכים לפנייה.' },
    process: { eyebrow: 'איך זה עובד', title: 'פנייה קצרה, תיאום, ואז אוכל מוכן להגשה.' },
    story: { eyebrow: 'הסיפור של Nis', title: 'אירוח עם זיכרון, סדר וחום.', text: 'מטבח שמחבר ביתיות עם נראות יפה.', extraText: 'הכול נשען על חוויה אישית ומוקפדת.' },
    samples: { eyebrow: 'דוגמאות', title: 'כיוונים שאפשר להתחיל מהם.', text: 'רעיון מהיר לשולחן, מגש או מארז.' },
    coordination: { eyebrow: 'תיאום והזמנה', title: 'כמה פרטים קטנים לפני שסוגרים.' },
    realMedia: { eyebrow: 'כך זה נראה', title: 'תמונות ורגעים אמיתיים מהאירוח.', text: 'ההגשה חשובה כמו הטעם.' },
    gallery: { eyebrow: 'גלריה', title: 'רואים את הסגנון לפני שמחליטים.', text: 'תמונות שממחישות את הכיוון.' },
    bookingBasics: { eyebrow: 'בסיס להזמנה', title: 'מה כדאי להכין לפני שפונים?', text: 'תאריך, כמות, סוג אירוח וכיוון כללי.' },
    seo: { eyebrow: 'נראות בגוגל', title: 'איך המותג יופיע בחיפוש ובשיתוף?', text: 'כותרת ותיאור שמספרים בקצרה מה מיוחד ב-Nis.' },
    trust: { eyebrow: 'למה סומכים', title: 'שירות אישי, נראות יפה ואוכל שמרגיש נכון.' },
    faq: { eyebrow: 'שאלות נפוצות', title: 'כל מה שחשוב לדעת לפני שממשיכים.', text: 'תשובות קצרות שמסדרות את התמונה.' },
    contact: { eyebrow: 'יצירת קשר', title: 'מספרים מה צריך ומקבלים כיוון מתאים.', text: 'אפשר דרך וואטסאפ או טלפון.', extraText: 'נחזור עם כיוון מותאם לאירוח.' },
  },
  siteMicrocopy: {
    navExperiencesLabel: 'מה מזמינים',
    navGalleryLabel: 'גלריה',
    navProcessLabel: 'איך זה עובד',
    navFaqLabel: 'שאלות',
    navContactLabel: 'יצירת קשר',
    galleryAllLabel: 'הכל',
    galleryTablesLabel: 'שולחנות',
    galleryTraysLabel: 'מגשים',
    gallerySaladsLabel: 'סלטים',
    galleryCoffeeLabel: 'קפה',
    galleryFishLabel: 'דגים',
    topbarWhatsappLabel: 'וואטסאפ',
    footerTagline: 'אוכל של בית, גימור של בוטיק.',
    footerWhatsappLabel: 'וואטסאפ',
    studioLoginLabel: 'כניסת ניהול',
    floatingWhatsappAria: 'דברו איתנו בוואטסאפ',
    mobileActionsAria: 'פעולות מהירות ליצירת קשר',
    mobileWhatsappLabel: 'וואטסאפ',
    mobilePhoneLabel: 'טלפון',
    heroPrimaryCta: 'דברו איתנו בוואטסאפ',
    heroSecondaryCta: 'ראו איך זה נראה',
    heroMicrocopy: 'אפשר גם למלא את הטופס ולשלוח פנייה מסודרת.',
    heroShowcaseTitle: 'שבתות, אירוח קטן ומארזים',
    heroShowcaseText: 'אותה שפה של טעם, נראות ושקט למארח.',
    heroVideoChip: 'רגעים אמיתיים מהאירוח',
    experienceCta: 'לפתוח שיחה על החוויה הזו',
    contactPrimaryCta: 'קבלו הצעה מותאמת בוואטסאפ',
    contactPhoneCta: 'התקשרו עכשיו',
    contactLocation: 'ביתר עילית',
    contactPromiseHeading: 'מה קורה אחרי הפנייה?',
    formNameLabel: 'שם מלא',
    formPhoneLabel: 'טלפון',
    formEmailLabel: 'מייל',
    formInterestLabel: 'במה אתם מתעניינים?',
    formDateLabel: 'תאריך רצוי',
    formGuestsLabel: 'מספר סועדים',
    formDeliveryLabel: 'אופן קבלה מועדף',
    formMessageLabel: 'הודעה קצרה',
    formSubmitLabel: 'שלחו פנייה בוואטסאפ',
    whatsappTopbarMessage: 'שלום Nis, אשמח ליצור קשר.',
    whatsappHeroTopic: 'קייטרינג בוטיק לאירוח',
    whatsappContactMessage: 'שלום Nis, אשמח ליצור קשר לגבי הזמנה.',
    whatsappFooterMessage: 'שלום Nis, אשמח לקבל פרטים.',
    whatsappFloatingMessage: 'שלום Nis, אשמח לקבל פרטים דרך האתר.',
  },
  seoTopics: ['קייטרינג בוטיק', 'שבתות', 'מגשי אירוח'],
  services: [
    {
      title: 'ניס בטעם של שבת',
      subtitle: 'שבת רגועה יותר, עם שולחן מוכן.',
      description: 'תפריט שבת עשיר שמגיע מוכן להגשה.',
      bestFor: 'משפחות ומארחים שרוצים שקט לפני שבת.',
      promise: 'אוכל ביתי מסודר, נעים ומכובד.',
      details: ['סלטים', 'דגים', 'עיקריות', 'קינוחים'],
      cta: 'להזמנת תפריט שבת',
      image: image('/media/food/events/salmon-skewers-lemon.webp', 1500, 2000, '(max-width: 720px) 100vw, 45vw'),
      icon: ChefHat,
    },
    {
      title: 'ניס בכיס',
      subtitle: 'אירוח קטן, רושם גדול.',
      description: 'מגשי אירוח ופינגר פוד לאירועים קטנים.',
      bestFor: 'אירוח משפחתי, עסקי ומפגשים קטנים.',
      promise: 'מוכן להיפתח יפה על השולחן.',
      details: ['מגשים', 'בראנץ׳', 'ביסים קטנים'],
      cta: 'דברו איתנו על מגשי אירוח',
      image: fallbackFoodImage,
      icon: Utensils,
    },
    {
      title: 'Travel Nis',
      subtitle: 'פינוק בוטיק שלוקחים איתכם.',
      description: 'מארזי דרך ופיקניק מסודרים ונוחים.',
      bestFor: 'טיולים, ימי כיף ויציאות מיוחדות.',
      promise: 'נוח לקחת, נעים לפתוח וטעים לאכול.',
      details: ['מארז זוגי', 'מארז משפחתי', 'פיקניק'],
      cta: 'להזמנת מארז דרך',
      image: image('/media/food/events/mini-burger-trays.webp', 899, 1599, '(max-width: 720px) 100vw, 33vw'),
      icon: Package,
    },
  ],
  signatureMoments: [
    { title: 'נראות מוכנה לשולחן', text: 'האירוח מרגיש מסודר כבר מהפתיחה.', image: fallbackFoodImage },
    { title: 'טעם חם ומוכר', text: 'אוכל ביתי עם הגשה מוקפדת.', image: fallbackFoodImage },
  ],
  storyMoments: [
    { title: 'זיכרון של אירוח', text: 'ביתיות, סדר וחום.' },
    { title: 'מטבח מוקפד', text: 'אוכל שמכבד את הרגע.' },
  ],
  trustCards: [
    card('שירות אישי', 'תיאום ישיר וענייני.', HeartHandshake),
    card('נראות מוקפדת', 'מוכן להיפתח יפה על השולחן.', Sparkles),
    card('זמינות נוחה', 'פנייה קצרה שמקדמת מהר.', Phone),
  ],
  videoMedia: {
    saladCupsPrep: '/media/food/nis-salad-cups-prep.mp4',
    eventVideo: '/media/food/events/nis-event-table-video.mp4',
  },
  whatsappBase: 'https://wa.me/972503502615',
};
